spring:
  application:
    name: projet-bibliotheque
  security:
    user:
      name: teddy       # Utilisateur en mémoire pour Spring Security
      password: teddy123
      roles: ADMIN

  datasource:
    url: jdbc:postgresql://localhost:5432/projet-bibliotheque?sslmode=disable
    username: postgres
    password: Teddy
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update            # ✅ Crée/Met à jour automatiquement les tables selon les entités
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"               # Expose tous les endpoints Actuator

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

pexels:
  api-key: "cfh1SFTxeNyLrZouc0IrIWCIeFJo76R0J34h2w2v9opZyZJgB3AcvCoT"

logging:
  level:
    com.pkf.projet_bibliotheque: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
